db:
  name: wp-database
  labels:
    app: db
    env: stage
    stack: wordpress
  image:
    repository: mariadb
    tag: "10.6.4-focal"
    pullPolicy: IfNotPresent
  replicas: 3
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    APP_ENV: stage
  containerPorts:
    mysql: 3306
  # volume:
  #     name: nginx-proxy-cache-store
  #     mount:
  #         path: /var/lib/mysql
  #         name: nginx-proxy-cache-store
  #     storage: 1T
  #     nfs:
  #         path: /shared_volume
  #         server: dev-cache-filestore.internal.gdev.postmedia.digital
  #     claim:
  #         name: nginx-proxy-cache-store-claim