#default
#common stuff is put here

db:
  name: wp-database
  labels:
    app: db
    env: dev
    stack: wordpress
  image:
    repository: mariadb:10.6.4-focal
    tag: v1
    pullPolicy: Always
  replicas: 1
  configmap:
    ## KEY: "value"
    MYSQL_DATABASE: wordpress
    MYSQL_USER: wordpress
    APP_ENV: dev
  containerPorts:
    mysql: 3306
  # volume:
  #     name: nginx-proxy-cache-store
  #     mount:
  #         path: /var/lib/mysql
  #         name: nginx-proxy-cache-store
  #     storage: 1T
  #     nfs:
  #         path: /shared_volume
  #         server: dev-cache-filestore.internal.gdev.postmedia.digital
  #     claim:
  #         name: nginx-proxy-cache-store-claim+